import { useState } from 'react';
import type { LiveDetail, LiveFrame, LiveItem, LivePlayerView, LiveRecipe } from '@coach/ui';
import { ChampionIcon, ItemIcon, RuneIcon, SpellIcon } from '../assets';
import './live-companion.css';
const clock=(s:number)=>`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`;
function Items({items}:{items:LiveItem[]}) {return <div className="lc-items">{items.map((i,n)=><span key={`${i.id}-${n}`} title={i.reason??i.name}><ItemIcon id={i.id} size={36}/><span>{i.name}<small>{i.gold} gold</small></span></span>)}</div>}
function Recipe({node}:{node:LiveRecipe}) {return <li className={node.owned?'lc-owned':''}><div><ItemIcon id={node.id} size={28}/><span>{node.name}<small>{node.owned?'Owned':`${node.remaining} gold remaining`}</small></span></div>{node.children.length>0&&<ul>{node.children.map((c,i)=><Recipe key={`${c.id}-${i}`} node={c}/>)}</ul>}</li>}
function Player({p}:{p:LivePlayerView}) {return <article className={`lc-player ${p.isMe?'lc-me':''}`}><header><ChampionIcon champion={/^\d+$/.test(p.champion)?Number(p.champion):p.champion} size={52}/><div><strong>{p.name??p.champion}{p.isMe?' · You':''}</strong><small>{p.champion} · {p.role||'Role unconfirmed'}</small></div><span className="lc-rank">{p.rank??'Rank unavailable'}</span></header><div className="lc-player-stats"><span><small>Level</small>{p.level??'—'}</span><span><small>Live K / D / A</small>{p.kills===null?'—':`${p.kills} / ${p.deaths} / ${p.assists}`}</span><span><small>CS</small>{p.cs??'—'}</span></div><div className="lc-loadout"><small>Spells: {p.spells?.join(" + ")||"Not reported"}</small><div className="lc-inventory">{p.runes?.map((r,i)=><span title={r.name} key={`${r.id}-${i}`}><RuneIcon id={r.id} size={24}/></span>)}</div></div><div className="lc-inventory">{p.items.map((id,i)=><ItemIcon key={`${id}-${i}`} id={id}/>)}</div>{p.history.length?p.history.map((h,i)=><p className="lc-tag" key={i}>{h}</p>):<small>Champion history and tendencies unavailable.</small>}</article>}
const roles=['TOP','JUNGLE','MIDDLE','BOTTOM','UTILITY'];
const roleKey=(v:string|null)=>({MID:'MIDDLE',BOT:'BOTTOM',ADC:'BOTTOM',SUPPORT:'UTILITY'}[v?.toUpperCase()??'']??v?.toUpperCase());
function Teams({d}:{d:LiveDetail}) {
 const pairs:{left?:LivePlayerView;right?:LivePlayerView;label:string}[]=[];
 const a=[...d.players.allies], b=[...d.players.enemies];
 for(const role of roles){const ai=a.findIndex(p=>roleKey(p.role)===role),bi=b.findIndex(p=>roleKey(p.role)===role);if(ai>=0||bi>=0)pairs.push({left:ai>=0?a.splice(ai,1)[0]:undefined,right:bi>=0?b.splice(bi,1)[0]:undefined,label:role});}
 while(a.length||b.length)pairs.push({left:a.shift(),right:b.shift(),label:'Unconfirmed'});
 return <section aria-label="Summoner insights" className="lc-matchups"><div className="lc-team-label"><strong>Your team</strong><strong>Enemy team</strong></div>{pairs.map((r,i)=><div className="lc-matchup" key={i}>{r.left?<Player p={r.left}/>:<div className="lc-empty">Player not revealed</div>}<span className="lc-role">{r.label}</span>{r.right?<Player p={r.right}/>:<div className="lc-empty">Player not revealed</div>}</div>)}{d.playerNotes.length>0&&<article className="lc-panel"><h2>Your champion experience</h2>{d.playerNotes.map((n,i)=><p key={i}>{n}</p>)}</article>}</section>;
}
function Build({d,frame}:{d:LiveDetail;frame:LiveFrame}) {
 return <div className="lc-build"><aside className="lc-panel lc-route"><h2>Purchase order</h2><small>Re-evaluated with your gold, inventory and the match.</small>{d.buyNow.length>0?<ol>{d.buyNow.map((i,n)=><li key={`${i.id}-${n}`}><ItemIcon id={i.id} size={36}/><strong>{i.name}</strong><small>{i.gold} gold · {i.targetName??'Immediate purchase'}</small>{i.reason&&<p>{i.reason}</p>}</li>)}</ol>:<p>{frame.phase==='live'?'No supported purchase at this budget.':'Purchases begin when the game starts.'}</p>}
 <div className="lc-budget"><span>Current gold<strong>{frame.gold===null?'—':Math.floor(frame.gold)}</strong></span><span>After shopping<strong>{d.leftover===null?'—':Math.floor(d.leftover)}</strong></span></div>{d.deferred.length>0&&<p>Keep unfinished: {d.deferred.join(', ')}.</p>}
 <h3>Target build</h3>{d.targets.map((t,i)=><div className="lc-target" key={`${t.id}-${i}`}><b>{i+1}</b><ItemIcon id={t.id}/><span>{t.name}<small>{t.remaining} gold remaining{t.at!==null?` · est. ${clock(t.at)}`:''}</small></span></div>)}<small>Timing is conditional on income. The target order may change.</small></aside>
 <div className="lc-middle"><section className="lc-panel"><h2>Recommended runes</h2>{d.runes.length?<div className="lc-runes">{[...new Set(d.runes.map(r=>r.group))].map(group=><div key={group}><h3>{group}</h3>{d.runes.filter(r=>r.group===group).map((r,i)=><div className="lc-rune" key={`${r.id}-${i}`} title={r.why}><RuneIcon id={r.id} size={38}/><span>{r.name}<small>{r.why}</small></span></div>)}</div>)}</div>:<p>Contextual rune recommendations unavailable.</p>}<details><summary>Equipped runes</summary>{d.equippedRunes.length?d.equippedRunes.map((r,i)=><div className="lc-rune" key={`${r.id}-${i}`}><RuneIcon id={r.id}/>{r.name}</div>):<p>Not reported by the game.</p>}</details></section>
 <section className="lc-panel"><h2>Skill order</h2><p>{d.nextSkill??(d.skillOrder.length?`Priority: ${d.skillOrder.join(' → ')}`:'No supported skill recommendation yet.')}</p><div className="lc-skill-grid" role="table" aria-label="Ability order by level"><div className="lc-skill-row"><b>Level</b>{Array.from({length:18},(_,i)=><span key={i}>{i+1}</span>)}</div>{['Q','W','E','R'].map((key,index)=><div className="lc-skill-row" key={key}><b>{key}</b>{Array.from({length:18},(_,i)=><span className={d.skillSequence[i]===index+1?'lc-skill-on':''} key={i}>{d.skillSequence[i]===index+1?key:'·'}</span>)}</div>)}</div><small>{d.skillSequence.length?'Reference sequence; adapt to the current match.':'Level-by-level reference unavailable; no sequence is invented.'}</small>{d.skillRanks.length>0&&<p>Equipped ranks: {d.skillRanks.map((n,i)=>`${['Q','W','E','R'][i]} ${n}`).join(' · ')}</p>}</section>
 <section className="lc-panel"><h2>Component trees</h2><small>Owned pieces are credited once. Prices include remaining combination costs.</small>{d.recipes.length?d.recipes.map((r,i)=><details key={`${r.id}-${i}`} open={i===0}><summary>{r.name} · {r.remaining} gold</summary><ul className="lc-tree"><Recipe node={r}/></ul></details>):<p>Recipe data unavailable for this state.</p>}</section></div>
 <aside className="lc-right"><section className="lc-panel"><h2>Summoner spells</h2>{d.spells.length?d.spells.map(s=><div className="lc-rune" key={s.name}>{s.key!==null&&<SpellIcon id={s.key} size={32}/>}<span>{s.name}<small>{s.why}</small></span></div>):<p>Recommendations unavailable.</p>}<h3>Equipped</h3><p>{d.equippedSpells.join(' + ')||'Not reported'}</p></section><section className="lc-panel"><h2>Starting items</h2><Items items={d.starter}/>{!d.starter.length&&<p>Unavailable for this setup.</p>}</section><section className="lc-panel"><h2>Situational alternatives</h2>{d.alternatives.map((i,n)=><div className="lc-alternative" key={`${i.id}-${n}`}><Items items={[i]}/><p>{i.reason}</p></div>)}{!d.alternatives.length&&<p>No supported alternative yet.</p>}</section></aside></div>;
}
export function LiveCompanion({frame}:{frame:LiveFrame}) {
 const [tab,setTab]=useState<'build'|'teams'>('build');const d=frame.detail!;
 return <section className="lc"><div className="lc-toolbar"><h2>Live Companion <span className="lc-live">{frame.phase}</span></h2><div role="tablist" aria-label="Live companion views"><button role="tab" aria-selected={tab==='teams'} onClick={()=>setTab('teams')}>Summoner Insights</button><button role="tab" aria-selected={tab==='build'} onClick={()=>setTab('build')}>Recommended Build</button></div></div>
 {d.source!=='contextual'&&<p className="lc-source" role="status">{d.source==='synthetic'?'Test server: synthetic knowledge. This is not a validated real-match build.':'Limited local guidance: contextual build data is unavailable.'}</p>}
 <div className="lc-composition"><section><h3>Your team</h3><div className="lc-inventory">{d.players.allies.map((p,i)=><ChampionIcon key={i} champion={/^\d+$/.test(p.champion)?Number(p.champion):p.champion}/>)}</div><p>{d.teamNotes[0]??'Composition analysis unavailable.'}</p></section><section className="lc-center"><h3>Matchup insights</h3><p>{frame.sections.find(s=>s.title==='Main concern')?.lines[0]??d.enemyNotes[0]??'Analysis updates as picks and match information become available.'}</p><small>Early / Mid / Late: no validated team power curve available.</small></section><section><h3>Enemy team</h3><div className="lc-inventory">{d.players.enemies.map((p,i)=><ChampionIcon key={i} champion={/^\d+$/.test(p.champion)?Number(p.champion):p.champion}/>)}</div>{d.damage?<><div className="lc-damage"><span style={{flex:Math.max(0,d.damage.physical)}}/><span style={{flex:Math.max(0,d.damage.magic)}}/><span style={{flex:Math.max(0,d.damage.true)}}/></div><small>Estimated kit damage profile · physical / magic / true</small></>:<p>Damage profile unavailable.</p>}</section></div>
 {tab==='teams'?<Teams d={d}/>:<Build d={d} frame={frame}/>}
 </section>;
}
